const { contextBridge, ipcRenderer } = require('electron')
const invoke = (ch, ...a) => ipcRenderer.invoke(ch, ...a)
const on = (ch, fn) => { ipcRenderer.on(ch, fn); return () => ipcRenderer.removeListener(ch, fn) }

// Transfer the worklet's port once; PCM then travels straight to the main
// process without scheduling a callback on the window's JavaScript thread.
window.addEventListener('message', event => {
  if (event.source !== window || event.data?.type !== 'lokal:audio-output-port' || event.ports.length !== 1) return
  ipcRenderer.postMessage('audio-output:connect', null, [event.ports[0]])
})

contextBridge.exposeInMainWorld('electron', {
  isElectron: true,
  nativeAudio: {
    directTransport: true,
    devices: () => invoke('audio-output:devices'),
    diagnostics: () => invoke('audio-output:diagnostics'),
    open: options => invoke('audio-output:open', options),
    write: (session, samples) => invoke('audio-output:write', session, samples),
    flush: session => invoke('audio-output:flush', session),
    close: () => invoke('audio-output:close'),
  },
  minimize: () => invoke('window:minimize'),
  setBackgroundColor: (color) => invoke('window:setBackgroundColor', color),
  maximize: () => invoke('window:maximize'),
  close: () => invoke('window:close'),
  setAlwaysOnTop: (flag) => invoke('window:setAlwaysOnTop', flag),
  setWindowSize: (width, height) => invoke('window:setSize', width, height),
  setMiniMode: (enabled) => invoke('window:setMiniMode', enabled),
  getWindowSize: () => invoke('window:getSize'),
  fitMiniHeight: (height) => invoke('window:fitMiniHeight', height),
  refreshHitRegions: () => invoke('window:refreshHitRegions'),
  onNavigationHistory: (fn) => on('navigation:history', (_, direction) => fn(direction)),
  onWindowVisibility: (fn) => on('window:visibility', (_, hidden) => fn(!!hidden)),
  isWindowHidden: () => invoke('window:isHidden'),
  openExternal: (url) => invoke('shell:openExternal', url),
  openFolder: () => invoke('dialog:openFolder'),
  openFile: (f) => invoke('dialog:openFile', f),
  readFileBinary: (fp) => invoke('dialog:readFileBinary', fp),
  readFileAsDataURL: (fp) => invoke('dialog:readFileAsDataURL', fp),

  log: (level, message) => ipcRenderer.send('app-log', { level, message }),
  openLogs: () => ipcRenderer.send('open-logs'),
  updaterDownload: () => invoke('updater:download'),
  scanFolder: (f) => invoke('scanner:scan', f),
  resolveFileToPlay: (f) => invoke('scanner:resolveFileToPlay', f),
  onOpenFileRequest: (fn) => on('player:openFile', (_, filePath) => fn(filePath)),
  updateThumbarState: (state) => invoke('thumbar:updateState', state),
  onThumbarCommand: (fn) => {
    const channels = {
      'thumbar:previous': 'previous',
      'thumbar:toggle-play': 'toggle-play',
      'thumbar:next': 'next',
      'thumbar:toggle-like': 'toggle-like',
    }
    const handler = (action) => () => fn(action)
    const bound = Object.fromEntries(Object.entries(channels).map(([channel, action]) => [channel, handler(action)]))
    for (const [channel, cb] of Object.entries(bound)) ipcRenderer.on(channel, cb)
    return () => { for (const [channel, cb] of Object.entries(bound)) ipcRenderer.removeListener(channel, cb) }
  },
  getTracks: (o) => invoke('scanner:getTracks', o),
  getMissingTracks: () => invoke('scanner:getMissingTracks'),
  searchTracks: (q) => invoke('scanner:search', q),
  libraryKeys: () => invoke('library:keys'),
  searchLyrics: (q) => invoke('scanner:searchLyrics', q),
  getArtists: () => invoke('scanner:getArtists'),
  getArtistsPage: (opts) => invoke('scanner:getArtistsPage', opts),
  getArtist: (id) => invoke('scanner:getArtist', id),
  getAlbumTracks: (a) => invoke('scanner:getAlbumTracks', a),
  getAllAlbums: () => invoke('scanner:getAllAlbums'),
  searchAlbums: (q) => invoke('scanner:searchAlbums', q),
  onScanProgress: (fn) => on('scanner:progress', fn),
  getSuggestions: (uid) => invoke('scanner:getSuggestions', uid),
  getHistory: (uid, l) => invoke('scanner:getHistory', uid, l),
  getMixes: (uid) => invoke('scanner:getMixes', uid),
  getRelated: (id, uid) => invoke('scanner:getRelated', id, uid),
  checkDuplicates: () => invoke('scanner:checkDuplicates'),
  checkPossibleDuplicates: () => invoke('scanner:checkPossibleDuplicates'),
  mergeDuplicates: (keepId, removeIds) => invoke('scanner:mergeDuplicates', keepId, removeIds),
  mergeAllDuplicates: () => invoke('scanner:mergeAllDuplicates'),
  deleteTracks: (ids) => invoke('scanner:deleteTracks', ids),
  deleteTrackByPath: (filePath) => invoke('scanner:deleteTrackByPath', filePath),
  incrementPlayTime: (id, uid, secs) => invoke('scanner:incrementPlayTime', id, uid, secs),
  getRandomTrack: () => invoke('scanner:getRandomTrack'),
  getTopGenres: () => invoke('scanner:getTopGenres'),
  getAllGenres: () => invoke('scanner:getAllGenres'),
  fetchMissingGenres: () => invoke('scanner:fetchMissingGenres'),
  genresStatus: () => invoke('scanner:genresStatus'),
  readFileAsDataURL: (path) => ipcRenderer.invoke('dialog:readFileAsDataURL', path),
  
  getPlaylists: (uid) => invoke('scanner:getPlaylists', uid),
  createPlaylist: (n, uid, d) => invoke('scanner:createPlaylist', n, uid, d),
  updatePlaylist: (id, d) => invoke('scanner:updatePlaylist', id, d),
  smartPlaylistPreview: (rules, uid) => invoke('playlist:smartPreview', rules, uid),
  addToPlaylist: (pl, t) => invoke('scanner:addToPlaylist', pl, t),
  removeFromPlaylist: (pl, t) => invoke('scanner:removeFromPlaylist', pl, t),
  getPlaylistTracks: (pl) => invoke('scanner:getPlaylistTracks', pl),
  deletePlaylist: (pl) => invoke('scanner:deletePlaylist', pl),
  playlistImport: (name, entries, uid) => invoke('playlist:import', name, entries, uid),
  playlistImportFile: (name, fileContent, fileType, uid) => invoke('playlist:importFile', name, fileContent, fileType, uid),
  previewExternalPlaylistImport: (payload) => invoke('playlist:previewExternalImport', payload),
  importExternalPlaylist: (payload) => invoke('playlist:importExternalFile', payload),
  importExternalTrackMetadata: (payload) => invoke('playlist:importExternalMetadata', payload),
  previewLinkPlaylist: (payload) => invoke('playlist:previewLink', payload),
  importLinkPlaylist: (payload) => invoke('playlist:importLink', payload),
  resolveGhostTrack: (ghostTrackId, targetTrackId, options = {}) => invoke('playlist:resolveGhostTrack', ghostTrackId, targetTrackId, options),
  reorderPlaylist: (pl, trackIds) => invoke('scanner:reorderPlaylist', pl, trackIds),
  deduplicatePlaylist: (pl) => invoke('scanner:deduplicatePlaylist', pl),

  
  toggleLike: (t, uid) => invoke('scanner:toggleLike', t, uid),
  setLike: (t, uid, liked) => invoke('scanner:setLike', t, uid, liked),
  getLikedTracks: (uid) => invoke('scanner:getLikedTracks', uid),
  historyExport: (uid, format) => invoke('history:export', uid, format),

  
  artistUpdateBio: (id, b) => invoke('artist:updateBio', id, b),
  artistSetImage: (id, d) => invoke('artist:setImage', id, d),
  artistSetImageUrl: (id, url) => invoke('artist:setImageUrl', id, url),
  artistRefreshMetadata: (id, opts) => invoke('artist:refreshMetadata', id, opts),
  artistsRefreshAllMetadata: (opts) => invoke('artists:refreshAllMetadata', opts),
  artistsRefreshAllStatus: () => invoke('artists:refreshAllStatus'),
  artistsRefreshAllCancel: () => invoke('artists:refreshAllCancel'),
  artistSearchMetadata: (query, opts) => invoke('artist:searchMetadata', query, opts),
  artistApplyMetadataSelection: (id, selection, mode) => invoke('artist:applyMetadataSelection', id, selection, mode),
  artistClearImageOverride: (id) => invoke('artist:clearImageOverride', id),
  artistRename: (id, n) => invoke('artist:rename', id, n),
  artistMerge: (s, t) => invoke('artist:merge', s, t),
  artistDelete: (id) => invoke('artist:delete', id),
  trackSetArtwork: (id, d) => invoke('track:setArtwork', id, d),
  trackSetGenre: (id, genre) => invoke('track:setGenre', id, genre),
  updateTrack: (id, data) => invoke('track:update', id, data),
  batchUpdateTracks: (trackIds, operations) => invoke('track:batchUpdate', trackIds, operations),
  updateTrackArtwork: (id, imageData) => invoke('track:setArtwork', id, imageData),
  fetchExternalArtwork: (id, title, artist) => invoke('track:fetchExternalArtwork', id, title, artist),
  setManualGenre: (data) => invoke('scanner:setManualGenre', data),

  
  getLyrics: (id, ti, ar, al, d, fp, opts) => invoke('lyrics:get', id, ti, ar, al, d, fp, opts),
  getLyricsFrom: (providerId, id, ti, ar, al, d, fp) => invoke('lyrics:getFrom', providerId, id, ti, ar, al, d, fp),
  getLyricsSources: () => invoke('lyrics:sources'),
  romanizeLyrics: (id, lines) => invoke('lyrics:romanize', id, lines),
  detectLyricsLanguage: (id, lines) => invoke('lyrics:detectLanguage', id, lines),
  translateLyrics: (id, lines, targetLang) => invoke('lyrics:translate', id, lines, targetLang),
  clearLyricsCache: (id) => invoke('lyrics:clearCache', id),
  importLyrics: (id, c, t, fp) => invoke('lyrics:import', id, c, t, fp),
  clearLyricsDb: () => invoke('db:clearLyrics'),

  
  downloadYT: (url, opts) => invoke('downloader:download', url, opts),
  onlineSearch: (query, provider) => invoke('online:search', query, provider),
  onlineSave: (items) => invoke('online:save', items),
  onlinePrepare: (provider, id, force) => invoke('online:prepare', provider, id, force),
  onlineProviders: () => invoke('online:providers'),
  onlineGenre: (trackId) => invoke('online:genre', trackId),
  searchSpelling: (q) => invoke('online:spelling', q),
  discoveryArtwork: (items) => invoke('online:artwork', items),
  youtubeCatalogue: (options) => invoke('online:catalogue', options),
  youtubeAccount: (force = false) => invoke('online:account', force),
  youtubeSignIn: options => invoke('online:signIn', options),
  youtubeCancelSignIn: () => invoke('online:cancelSignIn'),
  onYoutubeSignInStatus: fn => on('online:signInStatus', (_, status) => fn(status)),
  youtubeDisconnect: () => invoke('online:disconnect'),
  youtubeAccountPlaylist: (playlistId) => invoke('online:accountPlaylist', playlistId),
  youtubeRadio: (videoId) => invoke('online:radio', videoId),
  youtubeSetLiked: (videoId, liked) => invoke('online:setAccountLiked', videoId, liked),
  onlineDownloadUrl: (provider, id) => invoke('online:downloadUrl', provider, id),
  addonsList: () => invoke('addons:list'),
  addonAlbum: (provider, id) => invoke('online:addonAlbum', provider, id),
  addonArtist: (provider, id) => invoke('online:addonArtist', provider, id),
  addonsInstall: (url) => invoke('addons:install', url),
  addonsRemove: (key) => invoke('addons:remove', key),
  addonsSetEnabled: (key, enabled) => invoke('addons:setEnabled', key, enabled),
  addonsSetSettings: (key, values) => invoke('addons:setSettings', key, values),
  addonsPackages: request => invoke('addons:packages', request),
  downloadPlaylist: (url, opts) => invoke('downloader:downloadPlaylist', url, opts),
  searchYT: (q, page) => invoke('downloader:search', q, page),
  searchYTArtist: (q, page) => invoke('downloader:searchArtist', q, page),
  linkInfo: (url) => invoke('downloader:linkInfo', url),
  cancelDownload: (id) => invoke('downloader:cancel', id),
  getDownloadQueue: () => invoke('downloader:queue'),
  retryDownload: (id) => invoke('downloader:retry', id),
  removeDownload: (id) => invoke('downloader:remove', id),
  cancelAllDownloads: () => invoke('downloader:cancelAll'),
  clearFinishedDownloads: () => invoke('downloader:clearFinished'),
  markDownloadsSeen: () => invoke('downloader:markSeen'),
  playableFile: (filePath) => invoke('media:playableFile', filePath),
  artworkMesh: (trackId) => invoke('artwork:mesh', trackId),
  cacheUsage: () => invoke('cache:usage'),
  cacheTrim: () => invoke('cache:trim'),
  cacheClear: () => invoke('cache:clear'),
  motionCover: (trackId) => invoke('artwork:motion', trackId),
  musicVideo: (trackId) => invoke('musicVideo:find', trackId),
  musicVideoDownload: (trackId) => invoke('musicVideo:download', trackId),
  musicVideoPrepare: (trackId) => invoke('musicVideo:prepare', trackId),
  musicVideoDeleteDownload: (trackId) => invoke('musicVideo:deleteDownload', trackId),
  musicVideoMigrationStatus: () => invoke('musicVideo:migrationStatus'),
  migrateMusicVideos: () => invoke('musicVideo:migrate'),
  musicVideoList: () => invoke('musicVideo:list'),
  musicVideoSave: (trackId, saved) => invoke('musicVideo:save', trackId, saved),
  onMusicVideoProgress: (fn) => on('musicVideo:progress', fn),
  indexAllMusicVideos: () => invoke('musicVideo:indexAll'),
  cancelMusicVideoIndex: () => invoke('musicVideo:cancelIndex'),
  onMusicVideoIndexProgress: (fn) => on('musicVideo:indexProgress', fn),
  indexAllLyrics: () => invoke('lyrics:indexAll'),
  cancelLyricsIndex: () => invoke('lyrics:cancelIndex'),
  onLyricsIndexProgress: (fn) => on('lyrics:indexProgress', fn),
  spotifyCanvasCheck: () => invoke('artwork:spotifyCheck'),
  soulseekStatus: () => invoke('soulseek:status'),
  soulseekSearch: (text) => invoke('soulseek:search', text),
  soulseekResults: (id) => invoke('soulseek:results', id),
  soulseekStopSearch: (id) => invoke('soulseek:stopSearch', id),
  soulseekFinishSearch: (id) => invoke('soulseek:finishSearch', id),
  soulseekDownload: (file, opts) => invoke('soulseek:download', file, opts),
  qualitySummary: () => invoke('quality:summary'),
  qualityList: (opts) => invoke('quality:list', opts),
  qualityStatus: () => invoke('quality:status'),
  qualityRead: (opts) => invoke('quality:read', opts),
  qualityCheck: (opts) => invoke('quality:check', opts),
  qualityCheckOne: (trackId) => invoke('quality:checkOne', trackId),
  qualityCancel: () => invoke('quality:cancel'),
  qualityBuyLinks: (trackId) => invoke('quality:buyLinks', trackId),
  onDownloadProgress: (fn) => on('downloader:progress', fn),
  getDownloadedPlaylists: () => invoke('downloader:getDownloadedPlaylists'),
  deleteDownloadedPlaylist: (id) => invoke('downloader:deleteDownloadedPlaylist', id),
  redownloadPlaylist: (id) => invoke('downloader:redownloadPlaylist', id),
  getPlaylistArchiveIds: (id) => invoke('downloader:getPlaylistArchiveIds', id),
  removeFromPlaylistArchive: (id, videoId) => invoke('downloader:removeFromPlaylistArchive', id, videoId),

  
  getToolsStatus: () => invoke('tools:status'),
  getYtDlpVersionStatus: () => invoke('tools:getYtDlpVersionStatus'),
  downloadYtDlp: () => invoke('tools:downloadYtDlp'),
  downloadFfmpeg: () => invoke('tools:downloadFfmpeg'),
  setCustomToolPath: (tool, path) => invoke('tools:setCustomPath', { tool, customPath: path }),
  detectTools: () => invoke('tools:detect'),
  onToolsDownloadProgress: (fn) => on('tools:downloadProgress', fn),

  
  getPerfSettings: () => invoke('perf:load'),
  savePerfSettings: (s) => invoke('perf:save', s),
  setMediaKeyPreference: (enabled) => invoke('mediaKeys:setPreferred', enabled),
  relaunchApp: () => ipcRenderer.send('relaunch-app'),
  onPerfSettings: (fn) => on('perf-settings', fn),

  
  getSettings: () => invoke('settings:get'),
  saveSettings: (s) => invoke('settings:save', s),
  exportAllData: () => invoke('settings:exportAll'),
  importAllData: (payload) => invoke('settings:importAll', payload),
  factoryReset: () => invoke('settings:factoryReset'),
  clearTracks: () => invoke('db:clearTracks'),
  getKeepCommaArtists: () => invoke('settings:getKeepCommaArtists'),

  setKeepCommaArtists: (artists) => invoke('settings:setKeepCommaArtists', artists),
  getTheme: () => invoke('settings:getTheme'),
  saveTheme: (theme, overrides) => invoke('settings:saveTheme', { theme, overrides }),
  reportRemoteState: (state) => ipcRenderer.send('remote:stateUpdate', state),
  onRemoteCommand: (fn) => on('remote:command', (_, payload) => fn(payload)),
  onSmtcShuffleRequest: (fn) => on('smtc:shuffleRequested', (_, value) => fn(value)),
  onSmtcRepeatRequest: (fn) => on('smtc:repeatRequested', (_, mode) => fn(mode)),

  
  register: (d) => invoke('user:register', d),
  login: (d) => invoke('user:login', d),
  listUsers: () => invoke('user:list'),
  deleteUser: (userId) => invoke('user:delete', userId),
  updateProfile: (d) => invoke('user:updateProfile', d),
  getUserStats: (uid) => invoke('user:getStats', uid),
  getUserRecap: (uid) => invoke('user:getRecap', uid),
  getListeningRecap: (uid, opts) => invoke('recaps:get', uid, opts),
  getListeningDays: (uid, opts) => invoke('recaps:days', uid, opts),
  getRecapTracks: (uid, opts) => invoke('recaps:tracks', uid, opts),
  getArtistPlays: (uid, artistId) => invoke('recaps:artistPlays', uid, artistId),
  getTrackPlays: (uid, trackId) => invoke('recaps:trackPlays', uid, trackId),
  getListeningPreferences: (uid) => invoke('recaps:getPreferences', uid),

  
  discordSetActivity: (t, p) => invoke('discord:setActivity', t, p),
  discordConnect: (id) => invoke('discord:connect', id),
  discordDisconnect: () => invoke('discord:disconnect'),
  discordStatus: () => invoke('discord:status'),

  
  lastfmConnect: (apiKey, apiSecret, token) => invoke('lastfm:connect', apiKey, apiSecret, token),
  lastfmGetArtistInfo: (artist) => invoke('lastfm:getArtistInfo', artist),
  lastfmGetTrackInfo: (artist, track) => invoke('lastfm:getTrackInfo', artist, track),
  lastfmGetSimilarArtists: (artist, limit) => invoke('lastfm:getSimilarArtists', artist, limit),
  lastfmSimilar: (artist, track, limit) => invoke('lastfm:similar', artist, track, limit),
  lastfmScrobble: (artist, track, album, duration, timestamp) => invoke('lastfm:scrobble', artist, track, album, duration, timestamp),
  lastfmUpdateNowPlaying: (artist, track, album, duration) => invoke('lastfm:updateNowPlaying', artist, track, album, duration),
  lastfmDiscovery: (page, force) => invoke('lastfm:discovery', page, force),
  lastfmCatalogue: (options) => invoke('lastfm:catalogue', options),
  lastfmLoved: (page) => invoke('lastfm:loved', page),
  lastfmSetLoved: (artist, track, loved) => invoke('lastfm:setLoved', artist, track, loved),
  lastfmSyncLikes: (userId, page) => invoke('lastfm:syncLikes', userId, page),
  listenbrainzStatus: () => invoke('listenbrainz:status'),
  listenbrainzConnect: (token) => invoke('listenbrainz:connect', token),
  listenbrainzDisconnect: () => invoke('listenbrainz:disconnect'),
  listenbrainzSetEnabled: (enabled) => invoke('listenbrainz:setEnabled', enabled),
  listenbrainzNowPlaying: (track) => invoke('listenbrainz:nowPlaying', track),
  listenbrainzSubmit: (track, listenedAt) => invoke('listenbrainz:submit', track, listenedAt),
  onLastfmAuthToken: (fn) => on('lastfm:auth-token', (_, token) => fn(token)),
  pluginsList: () => invoke('plugins:list'),
  pluginsReload: () => invoke('plugins:reload'),
  pluginsEnable: (pluginId) => invoke('plugins:enable', pluginId),
  pluginsDisable: (pluginId) => invoke('plugins:disable', pluginId),
  pluginsInstallFromFolder: (sourceFolderPath) => invoke('plugins:installFromFolder', sourceFolderPath),
  pluginsRemove: (pluginId) => invoke('plugins:remove', pluginId),
  updaterInstall: () => invoke('updater:install'),
  updaterCheck: () => invoke('updater:check'),
  getVersion: () => invoke('app:getVersion'),
  onUpdaterEvent: (cb) => {
    ipcRenderer.on('updater:available', (_, info) => cb('available', info))
    ipcRenderer.on('updater:progress', (_, p) => cb('progress', p))
    ipcRenderer.on('updater:ready', () => cb('ready'))
    ipcRenderer.on('updater:error', (_, msg) => cb('error', msg))
    return () => {
      ipcRenderer.removeAllListeners('updater:available')
      ipcRenderer.removeAllListeners('updater:progress')
      ipcRenderer.removeAllListeners('updater:ready')
      ipcRenderer.removeAllListeners('updater:error')
    }
  },
})
