const fs = require('fs')
const path = require('path')
const { spawnSync } = require('child_process')
const root = path.resolve(__dirname, '..')
const arch = process.argv[2] || process.arch
if (process.platform === 'darwin' && !['x64', 'arm64'].includes(arch)) throw new Error('Unsupported native audio architecture: ' + arch)
const cwd = path.join(root, 'native/audio-output')
const result = spawnSync(process.execPath, [require.resolve('node-gyp/bin/node-gyp.js'), 'rebuild', '--directory', cwd, '--arch=' + arch], { cwd: root, stdio: 'inherit' })
if (result.error || result.status !== 0) throw new Error('Native audio bridge build failed. Install the platform C++ build tools and retry.')
const target = path.join(root, 'electron/native')
fs.mkdirSync(target, { recursive: true })
fs.copyFileSync(path.join(cwd, 'build/Release/lokal_audio.node'), path.join(target, `audio-output.${process.platform}-${arch}.node`))
console.log('Prepared native audio output for ' + process.platform + '-' + arch)
