name: Notify Published Release

on:
  release:
    types: [published]

jobs:
  discord-announcement:
    runs-on: ubuntu-latest
    steps:
      - name: Send Public Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "content": "**A new Lokal update is now available!**",
            "embeds": [{
              "title": "Lokal ${{ github.event.release.tag_name }} is here!",
              "description": "The latest version of Lokal is now available for download!\n\n**What’s New:**\n${{ github.event.release.name }}\n\nGrab the update from GitHub below.",
              "url": "${{ github.event.release.html_url }}",
              "color": 3066993,
              "image": { "url": "https://i.imgur.com/KgjwTvk.png" },
              "footer": { "text": "Lokal - Local-first Music Player", "icon_url": "https://i.imgur.com/ZC3mEUC.png" }
            }]
          }' $DISCORD_WEBHOOK