name: Notify Published Release

on:
  release:
    types: [published]

jobs:
  discord-announcement:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification (Release Published)
        shell: bash
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          PAYLOAD=$(jq -n \
            --arg tag "${{ github.event.release.tag_name }}" \
            --arg name "${{ github.event.release.name }}" \
            --arg url "${{ github.event.release.html_url }}" \
            --arg image "https://i.imgur.com/KgjwTvk.png" \
            --arg footer_icon "https://i.imgur.com/ZC3mEUC.png" \
            --argjson color 3066993 \
            '{
              content: "**A new Lokal update is now available!**",
              embeds: [{
                title: "Lokal \($tag) is here!",
                description: "The latest version of Lokal is now available for download!\n\n**What’s New:**\n\($name)\n\nGrab the update from GitHub below.",
                url: $url,
                color: $color,
                image: { url: $image },
                footer: { text: "Lokal - Local-first Music Player", icon_url: $footer_icon }
              }]
            }'
          )

          curl -H "Content-Type: application/json" -d "$PAYLOAD" "$DISCORD_WEBHOOK"